### ISSUE TITLE
problem at init

### ISSUE THREAD

**Issue by andreasprlic** [biasmv/pv#84] opened 2015-03-01 23:37 UTC
Hi,

just update to latest checkout. There seems to be an issue during startup. I am getting a 

"ReferenceError: canvas is not defined" from this line in viewer.js:
isWebGLSupported: canvas.isWebGLSupported

A

**Comment by biasmv** [comment] 2015-03-02 06:37
Hi,

it's fixed now. This was caused by a bug in AMDclean. 

Best,
Marco

**Closed by biasmv** 2015-03-02 06:37 UTC

**Comment by andreasprlic** [comment] 2015-03-02 06:43
Thanks for the quick fix. I confirm it works again, also #82 .
